### ISSUE TITLE
Multi-thread PR testing?

### ISSUE THREAD

**Issue by fabiocos** [cms-sw/cms-bot#1201]
In regular PR tests single-threaded jobs are used in order to minimize the needed resources. This prevents to test possible race conditions, which are normally caught in IBs (at least) and debugged in a standalone way. As now we have multi-lumi test workflows where concurrent lumi processing is enabled, also in this case the concurrent lumi test will be ineffective in PR tests. 
@Dr15Jones to which extent is this an issue? In case we might consider enabling multi-threaded PR tests for a selected number of test workflows that are not routinely part of the short matrix but that might be of interest to check particular features.

@smuzaffar do you see hard limits in the test system preventing the implementationm o fsuch an option in case?

**Comment by Dr15Jones** [comment]
I think it is unlikely that multi-threaded pull request test will uncover race conditions. Anymore we only find those because of the large volume of RelVals we run.

I could see for pull requests which are explicitly doing multi-thread based changes that doing at least one threaded test would make sense.

**Comment by smuzaffar** [comment]
@fabiocos , for PR tests we run in single threaded mode to get reproducible results. I think with multi-threading ON the camparison jobs will show a lot of differences.

If can add an extra multi-threaded test (separate then normal relval tests) to run on selected workflows .

**Comment by smuzaffar** [comment]
Do we still need this? As now bot runs separate tests jobs for PRs, so we can add an additional test to run short matrix in multi-threaded mode ( or run such a test when explicitly enabled e.g. using `enable threading` ).  I agree with @Dr15Jones  that such test might not catch all the threading issue.

FYI @makortel

**Comment by fabiocos** [comment]
@smuzaffar my original idea was based on the experience of problems that may appear on small scale tests. Of course this cannot be exhaustive, reproducible, and it is more a limited way to catch macroscopic issues than to protect against any possible race conditions. At this point I let FWK and release managers @silviodonato @qliphy experts to decide based on their more recent experience

**Comment by silviodonato** [comment]
In the past this feature would have been useful for the migration to the new DQM modules and for the concurrent lumi processing. A part from this we encountered several time errors in IBs related to multithreading but, as you said, most likely they could not be caught in the PR test anyway because of the limited statistic.
One good example in favour of having a multithreaded workflow is https://github.com/cms-sw/cmssw/issues/32172.
So it would be nice to have a `enable threading` option, but I don't think it is very urgent

**Comment by makortel** [comment]
Another recent example, that probably would have caught multithreading problems before merge, was the first attempt of DD4Hep workflows (assuming `enable threading` would also be able to run extra workflows).

I agree with comments of @Dr15Jones and @silviodonato, i.e.
> So it would be nice to have a `enable threading` option, but I don't think it is very urgent

**Comment by smuzaffar** [comment]
bot now supports
```
enable threading
```
to run short matrix with `-t 4 -i all`. In case you want to pass extra parameters to runTheMatrix job then one can use `test parameters` command e.g.
```
test paramaters:
- relvals_opts_threading = -l workflow,numbers
```
