### ISSUE TITLE
signature delegation on specific packages

### ISSUE THREAD

**Issue by vlimant** [cms-sw/cms-bot#2043]
sparked from the discussion in https://github.com/cms-sw/cmssw/pull/42323 about PhysicsTools/NanoAODTools package that is @cms-sw/xpog-l2 signature, but actually belongs to CAT (@clelange @lenzip) ; would it be possible, instead of creating a CAT signature category, to have that package belong to xpog, with delegated signatures ?
might sound a bit silly, since we'd probably have to create a CAT group in https://github.com/cms-sw/cms-bot/blob/master/categories.py anyways to maintain names

**Comment by Dr15Jones** [comment]
Assign core

**Comment by smuzaffar** [comment]
@vlimant , `PhysicsTools/NanoAODTools` is new package and currently there is no one responsible for this. `xpog` signature on  https://github.com/cms-sw/cmssw/pull/42323 are due to changes in `PhysicsTools/NanoAOD` package. If the new package should belong to `CAT` then we should just add `cat` as a new cms-bot category. If it really belongs to `xpog` then we can add it under `xpog` and add @clelange @lenzip to the watcher list ( https://github.com/cms-sw/cms-bot/blob/master/watchers.yaml ) so that they can get notifications if someone proposes changes to this package
