### ISSUE TITLE
add igprof tests to jenkins workflows

### ISSUE THREAD

**Issue by slava77** [cms-sw/cms-bot#818]
The proposal is to instrument with mm (MEM_LIVE, MEM_TOTAL) and pp the following:
- 136.731 with 100 events; instrument step2 and 3 (the main target for me is step3, but I think that step2 is important for other areas)
- 21234.0 with 10 events [given that this starts from sim]; instrument step 1, 2 and 3
In each case a run in single thread is OK and is practical (given igprof MT [dis]functionality)

I think that for MEM_LIVE we should get reports at event end ```process.igprof.reportToFileAtEvent```

@kpedro88

**Comment by smuzaffar** [comment]
@slava77 , So running these commands
```
runTheMatrix.py -i all -l 136.731 --command '-n 100 --profile mp'
runTheMatrix.py -i all -l 136.731 --command '-n 100 --profile pp'
runTheMatrix.py -l 21234.0 --command '-n 10 --profile mp'
runTheMatrix.py -l 21234.0 --command '-n 10 --profile pp'
```
is enough ... correct? OR can we pass both pp and mp in single command? Is there any way to disable step4   and above (if these are not needed?)

**Comment by kpedro88** [comment]
@smuzaffar after making the cmsRun configs, one has to run igprof:
```
igprof -d -mp -z -o igprof.mp.gz cmsRun ...
igprof-analyse -d -v -g -r MEM_LIVE igprof.mp.gz > igreport.res
```

The two modes `mp` and `pp` have to run separately (I think).

The `cmsDriver.py` option `--profile mp` is definitely needed for the memory profile, but I'm not sure if `--profile pp` actually does anything important. Usually I run pp mode without that.

Maybe we want to augment `runTheMatrix.py` with an option that would execute all these profiling commands automatically?

I also recall that igprof had an issue running with input files accessed over xrootd (because the xrootd implementation always uses multiple threads). We should make sure this is handled correctly.

**Comment by makortel** [comment]
If/when we get there, can we have the output in (addition?) in the sqlite format and use (also?) igprof-navigator?

**Comment by smuzaffar** [comment]
we have been running igprof for these workflows in IBs for few weeks now (e.g. https://cmssdt.cern.ch/SDT/cgi-bin/igprof-navigator/CMSSW_10_6_X_2019-05-11-1100 ). Igprof navigator is also setup. Just browse through the links.
