### ISSUE TITLE
DQM monitor not showing memory reduction

### ISSUE THREAD

**Issue by fabiocos** [cms-sw/cms-bot#979]
During the scrutiny of cms-sw/cmssw#22955 I have noticed that the bot report was showing no memory variation, despited a number of tests being deleted. A manual run of dqmMemoryStats.py (dqmMemoryStats.py -i 10824.0_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2018_GenSimFull+DigiFull_2018+RecoFull_2018+ALCAFull_2018+HARVESTFull_2018//DQM_V0001_R000000001__Global__CMSSW_X_Y_Z__RECO.root -x --summary -u KiB) was on the contrary showin a reduction of some 25 KiB in the DQM memory budget induced by this PR:

diff -b new.log ref.log 

New 11530.10 KiB     HLT/BPH
Old   11555.89 KiB     HLT/BPH

New Total bytes: 381377.36 KiB
Old   Total bytes: 381403.15 KiB

This would seem a "feature" of https://github.com/cms-sw/cms-bot/blob/master/logRootQA.py .

The direct application of the command used by the bot ( https://github.com/cms-sw/cms-bot/blob/master/logRootQA.py#L165 ) gives the right answer:

dqmMemoryStats.py -x -u KiB -p3 -c0 -d2 --summary -r ../../../CMSSW_10_2_X_2018-04-25-1100/work/10824.0_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2018_GenSimFull+DigiFull_2018+RecoFull_2018+ALCAFull_2018+HARVESTFull_2018/DQM_V0001_R000000001__Global__CMSSW_X_Y_Z__RECO.root -i 10824.0_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2018_GenSimFull+DigiFull_2018+RecoFull_2018+ALCAFull_2018+HARVESTFull_2018/DQM_V0001_R000000001__Global__CMSSW_X_Y_Z__RECO.root 
********************************************************************************
************************* DQM level 2 folder breakdown *************************
********************************************************************************
-25.787 KiB      HLT/BPH
Total bytes: -25.787 KiB

**Comment by fabiocos** [comment]
@schneiml FYI

**Comment by davidlange6** [comment]
i notice is that the dqm size check was done on only 8 files

>> SUMMARY DQMHistoSizes: Histogram memory added: 0.0 KiB( 8 files compared)

likely due to something going wrong with the dqmMemoryStats call

Weird output /136.8311_RunJetHT2017F_reminiaod+RunJetHT2017F_reminiaod+REMINIAOD_data2017+HARVEST2017_REMINIAOD_data2017/step2_inDQM.root
('', 'Traceback (most recent call last):\n  File "/cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc630/cms/cmssw/CMSSW_10_2_X_2018-04-18-2300/bin/slc6_amd64_gcc630/dqmMemoryStats.py", line 132, in <module>\n    for (fn, v) in reader.read_objects():\n  File "/cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc630/cms/cmssw/CMSSW_10_2_X_2018-04-18-2300/python/DQMServices/FileIO/DQM.py", line 39, in read_objects_dqmio\n    object_type = self.DQMIO_TYPES[indices.Type]\nIndexError: list index out of range\n')
('', 'Traceback (most recent call last):\n  File "/cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc630/cms/cmssw/CMSSW_10_2_X_2018-04-18-2300/bin/slc6_amd64_gcc630/dqmMemoryStats.py", line 132, in <module>\n    for (fn, v) in reader.read_objects():\n  File "/cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc630/cms/cmssw/CMSSW_10_2_X_2018-04-18-2300/python/DQMServices/FileIO/DQM.py", line 39, in read_objects_dqmio\n    object_type = self.DQMIO_TYPES[indices.Type]\nIndexError: list index out of range\n')

**Comment by fabiocos** [comment]
@davidlange6 right, checking into this as well

**Comment by fabiocos** [comment]
A standalone test on 136.8311 does not show any error message (and 0 difference in the content), compatible with no B-tag specific folder

**Comment by schneiml** [comment]
Looks like I definitly did screw up a regexp here [1] (minus missing), though that does not entirely explain the problem yet...

[1] https://github.com/cms-sw/cms-bot/pull/972/files#diff-4cc3e6a66c2b94c385ce39318e327cbaR167

**Comment by schneiml** [comment]
... but the comparison in question was done using the old cms-bot code, looking at inDQM files. The "8 files compared" can be due to how files where counted back then (only those with changes or sth. in that direction).

The failure of dqmMemoryStats on these inDQM files is interesting and surprising, maybe @dmitrijus has an idea there. Either ways, the new code looks at harvesting output (which is in a different format), and should not show this problem (but maybe new ones).

**Comment by dmitrijus** [comment]
The weird output reported by David should be fixed now.

**Comment by smuzaffar** [comment]
this is addressed by #980
